version: "3"
services: 
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /my-app/node_modules
            - .:/my-app
        stdin_open: true